import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-[60px] border-b-2 border-black">header</div>
        <div> {children}</div>
        <div className="h-[60px] border-t-2 border-black">footer</div>
      </body>
    </html>
  );
}
